[workspace]
resolver = "3"
members = [
    "crates/inventium-core",
    "crates/inventium",
    "crates/inventium-curse",
    "crates/inventium-rinth",
    "crates/inventium-mcmod",
]

[workspace.dependencies]
anyhow = "1.0.100"
